CREATE TABLE perfil(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE usuario_perfil(
    usuario_id BIGINT NOT NULL,
    perfil_id BIGINT NOT NULL,

    PRIMARY KEY(usuario_id, perfil_id),
    CONSTRAINT USUARIOS_PERFIL_FK_USUARIO FOREIGN KEY(usuario_id) REFERENCES usuarios(id),
    CONSTRAINT USUARIOS_PERFIL_FK_PERFIL FOREIGN KEY(perfil_id) REFERENCES perfil(id)
);

INSERT INTO perfil(name) VALUES('ESTUDANTE');
INSERT INTO perfil(name) VALUES('INSTRUTOR');
INSERT INTO perfil(name) VALUES('MODERADOR');
INSERT INTO perfil(name) VALUES('ADMIN');

